### ISSUE TITLE
Script error when importing RNFFmpeg

### ISSUE THREAD

**Issue by manikandasankar** [tanersener/react-native-ffmpeg#13]
When importing **RNFFmpeg** in js file for android, it throws script error as cannot read property '**enableLogEvents**' of undefined.

import { RNFFmpeg } from 'react-native-ffmpeg';

**Comment by tanersener** [comment]
There are three working test applications under [react-native-ffmpeg-test](https://github.com/tanersener/react-native-ffmpeg-test) project. Can you compare your project with one of them?

**Comment by manikandasankar** [comment]
@tanersener Thanks for your help, i fixed this error.

But now i could not stream the video to **rtmp** server, i am getting error as **permission denied**

Error received on callback of execute command: /storage/emulated/0/Download/video.mp4: Permission denied

**Comment by tanersener** [comment]
This message is received when your application doesn't have necessary permissions to read files from phone.

Does your application have the following permission allowed in `AndroidManifest.xml`?

`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

**Comment by manikandasankar** [comment]
Yes i have this permission in my AndroidManifest.xml file, still i am getting that error

**Comment by manikandasankar** [comment]
It doesn't ask permission while giving it in AndroidManifest.xml file, so i used [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid) api from react-native, now it works fine for me.

Thanks for you help

**Comment by ozankonur** [comment]
> 
> 
> When importing **RNFFmpeg** in js file for android, it throws script error as cannot read property '**enableLogEvents**' of undefined.
> 
> import { RNFFmpeg } from 'react-native-ffmpeg';

How did you solve this @manikandasankar ?

**Comment by manikandasankar** [comment]
@ozankonur did you follow [this](https://github.com/tanersener/react-native-ffmpeg#231-android) step?

If you modify your settings.gradle properly with the package name(min | min-gpl | https | https-gpl | audio | video | full | full-gpl) it will work properly

**Comment by tanersener** [comment]
I apply the following steps when I get an error for `Android`. 

1. Stop (or kill if necesssary) all `npm` processes

2. Clear previous build with `rm -rf android/app/build`

3. Run the following command to clear watches and verify npm cache

    `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache verify && yarn install && npm start -- --reset-cache`

4. Run `react-native run-android` again.

After that If the error persists then try to run default test application from [react-native-ffmpeg-test](https://github.com/tanersener/react-native-ffmpeg-test) repository. If you can run default test-application successfully then you can assume you have a configuration error. Comparing your settings with default test-application will help you to solve your issue.

**Comment by ozankonur** [comment]
After remove the module then install it again solved the problem, thanks to both

**Comment by cagataykapuagasi** [comment]
I have same error on android:
undefined is not an object(evaluating 'RNFFmpegModule.enableLogEvents')
import { RNFFmpeg } from 'react-native-ffmpeg'; 
@manikandasankar  Could you tell me how do you fix the error?

**Comment by ashwinik-mdn** [comment]
@tanersener I get same error while using react-native-ffmpeg. 
Please look at logs from adb.

I ReactNativeJS: Loading react-native-ffmpeg.
I mobile-ffmpeg: Loading mobile-ffmpeg.
E unknown:ReactNative: Exception in native call
E unknown:ReactNative: java.lang.RuntimeException: Could not invoke RNFFmpegModule.enableLogEvents
E unknown:ReactNative:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
E unknown:ReactNative:   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
E unknown:ReactNative:   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:836)
E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:103)
E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:203)
E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:761)
E unknown:ReactNative: Caused by: java.lang.reflect.InvocationTargetException
E unknown:ReactNative:   at java.lang.reflect.Method.invoke(Native Method)
E unknown:ReactNative:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
E unknown:ReactNative:   ... 8 more
E unknown:ReactNative: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_sscanf" referenced by "/data/app/com.android.androidviewer-1/lib/arm/libavfilter.so"...
E unknown:ReactNative:   at java.lang.Runtime.loadLibrary0(Runtime.java:977)
E unknown:ReactNative:   at java.lang.System.loadLibrary(System.java:1530)
E unknown:ReactNative:   at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:116)
E unknown:ReactNative:   at com.arthenica.mobileffmpeg.Config.enableLogCallback(Config.java:190)
E unknown:ReactNative:   at com.arthenica.reactnative.RNFFmpegModule.enableLogEvents(RNFFmpegModule.java:160)
E unknown:ReactNative:   ... 10 more

I have followed the steps you have mentioned but result is same.

The test application run without any fail. Could you please look at above log and suggest me what is wrong.

**Comment by tanersener** [comment]
@ashwinik-mdn please see [Always fill the issue template ](https://github.com/tanersener/react-native-ffmpeg/issues/62). 

It is not possible to guess the cause of an error without knowing your environment, without understanding which steps failed for you.

**Comment by Thauan** [comment]
I went through this in a project it took me a few days, and I came to the conclusion that it was missing

MainApplication.java

the import:
import com.arthenica.reactnative.RNFFmpegPackage;

calling the new RNFFmpegPackage () method in getPackages ()

**Comment by Thauan** [comment]
I went through this in a project it took me a few days, and I came to the conclusion that it was missing

MainApplication.java

the import:
import com.arthenica.reactnative.RNFFmpegPackage;

calling the new RNFFmpegPackage () method in getPackages ()
