### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by sunkibaek** [tanersener/react-native-ffmpeg#50]
Hello,

Do you have a plan for supporting TypeScript types? If it is on your roadmap, I can PR a typescript file that I have made for my project.

BTW, thanks a lot for the great library! It works really well!

**Comment by tanersener** [comment]
Thanks for your suggestion. I’m planning to support `Flow` at some point, it looks easier to me. I can add `TypeScript` support too but I haven't use it before. So I need know that it won’t create a conflict with `Flow`.

**Comment by sunkibaek** [comment]
Okay, that sounds great.

**Comment by matthamil** [comment]
@tanersener TS shouldn't conflict with Flow. You can create a [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) that allows library consumers to have access to TS types without rewriting the library in TS.

**Comment by tanersener** [comment]
@matthamil I think I need to redefine `ReactNativeFFmpeg` class and its methods with TS types. I'll create another `.ts` file for that, named `index.ts`. But then I'll have both `index.js` and `index.ts`. After that how can I specify which file will be imported? I have `index.js` as main script in `package.json`, do I need to change that?

**Comment by matthamil** [comment]
@tanersener not at all. You will only need your current `index.js` file, and another type declarations file for TS support.

Your `index.js` won't need to be changed. You add a `types` field to the `package.json` that references `./index.d.ts` (the location of the type def file). 

As an example, check out Formik's [declaration file](https://unpkg.com/formik@1.5.1/dist/Formik.d.ts) that is published with their npm module. Library users will import JS, but the module has a type def file that TS users can take advantage of.

**Comment by matthamil** [comment]
If I find some time, I could PR a TS type def for you

**Comment by tanersener** [comment]
> As an example, check out Formik's [declaration file](https://unpkg.com/formik@1.5.1/dist/Formik.d.ts) that is published with their npm module. Library users will import JS, but the module has a type def file that TS users can take advantage of.

Thanks. I think I can do that in the `development` branch.

**Comment by matthamil** [comment]
Cool, let me know if you want me to look over the TS declaration file for you. Happy to help where ever I can!

**Comment by tanersener** [comment]
Hi @matthamil, I added `index.d.ts` file in the [development](https://github.com/tanersener/react-native-ffmpeg/tree/development) branch.

I'm testing it using `typescript` test-application from [react-native-ffmpeg-test](https://github.com/tanersener/react-native-ffmpeg-test) but it gives me `Property 'execute' does not exist on type 'typeof RNFFmpeg'` error. Do you have any idea about the reason?

**Comment by matthamil** [comment]
Here's [one of the lines](https://github.com/tanersener/react-native-ffmpeg-test/blob/c6ef8c8f180d0dc6bc9ee65c37799ead935dc663/typescript/src/Main.tsx#L9) throwing that error: 

```tsx
RNFFmpeg.execute(command, ' ')
```

You are invoking a method called `execute` on the reference to `RNFFmpeg`. Typescript thinks you are importing the class, not the instance of the class because the [named export](https://github.com/tanersener/react-native-ffmpeg/blob/fd6463b99b0e2981747c7b18b41748c5dbce8ab6/index.js#L324) matches the [same name as the TS named export](https://github.com/tanersener/react-native-ffmpeg/blob/e84ca28db2f6f1b843e8225f74f45c91d33574b6/index.d.ts#L56) for the class.

You aren't exporting a class from `index.js` though. You're exporting an instance of the class. You'll want to export an interface from `index.d.ts` instead of exporting a class since the actual class itself is not part of the public API.

Hope that helps!

**Comment by tanersener** [comment]
Thanks, I managed to fix all errors. But I'm not proud of the design, because JS class names and TS class names are not exactly the same. I intend to improve it over time.

**Comment by tanersener** [comment]
Fixed in `v0.3.2`.
