### ISSUE TITLE
[Question] Running on iOS device is 5x slower than running on iOS simulator 

### ISSUE THREAD

**Issue by iwantooxxoox** [tanersener/react-native-ffmpeg#77]
**Description**
I have tested the same command on both iOS device (iPhone X) and simulator, but it was much slower on real devices, just curious is it normal?

**Expected behavior**
Usually packages are running faster on device than simluator

**Environment**
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-native-ffmpeg": "^0.3.2",

ffmpeg package: react-native-ffmpeg/min-gpl-lts

Thanks

**Comment by tanersener** [comment]
Well, IPhone Simulator was the faster one on my tests too. Since Simulator is a simulator with a stronger CPU and more RAM I expect it to be faster than real devices. Especially for a process like `ffmpeg` which uses too much CPU and RAM.

Additionally, there is chance of a bug in the library too. Can you share the logs of your executions, so I can check a few things.

Btw, you can try disabling log and stats with `disableRedirection` method. It improves the speed on some occasions.
